### PR TITLE
maintainer updates

### PR DESCRIPTION
**Pull request by michmike**
Hello @goharbor/all-maintainers,

we would like to propose the addition of a new maintainer in Harbor to replace an existing one.

Daniel Pacak (@danielpacak) from Aqua Security has been instrumental in the architecture and delivery of the Pluggable Scanner work in 1.10. Daniel will have a specific job in the maintainers of Harbor, focusing on the security aspects and related work of Harbor and the pluggable scanner work.

Please vote on the new addition to the maintainers team of Harbor and congratulate Daniel on a great job so far!

In addition,  Mia Zhou (@zhoumeina) is departing our maintainers team. We thank Mia for her hard work and contributions to Harbor. Mia is changing her primary focus to work on other products, but will continue to help the Harbor team from time to time.

Signed-off-by: Michael Michael <michmike@cs.stanford.edu>

### CODE REVIEW

**Comment by steven-zou** [comment]
I'm co-working with @danielpacak for months. I'd like to say Daniel P is a good fit!

**Comment by michmike** [comment]
> Should we add a list of Emeritus maintainers for retiring ones?

i made the update. does it look good @hainingzhang ?

**Comment by kofj** [comment]
approved

**Comment by michmike** [comment]
> > Should we add a list of Emeritus maintainers for retiring ones?
> 
> i made the update. does it look good @hainingzhang ?

@hainingzhang  do we have any emeritus ones right now?

**Comment by steven-zou** [comment]
This nomination request is approved as we have got 4 votes already.

**Comment by steven-zou** [comment]
@michmike 

Will you send an annoucement mail to notify the community we have a new maintainer later? As usual action, we'll do that.

**Pull request merged**
