### PR TITLE
Retirement of maintainer cd1989

### PR DESCRIPTION
**Pull request by cd1989**
Signed-off-by: dechen <dechen@tencent.com>

Dear @goharbor/all-maintainers,

I'd like to retire from harbor maintainers due to new work arrangement. It's my honor to work with your alls to witness harbor step towards maturity and graduate from CNCF. Looking forwards to new cooperation in the future.

Thanks to VMware and henry, steven, kofj, ywk253100, wy65701436, reasonerjt and others to bring Harbor to community, it's an awesome project.

### CODE REVIEW

**Review by steven-zou — APPROVED** [review]
Approved!

**Review by mmpei — APPROVED** [review]
Good wishes.

**Review by reasonerjt — APPROVED** [review]

**Comment by reasonerjt** [comment]
@cd1989 
Thank you for the great work you've done.  Good luck!

**Comment by xaleeks** [comment]
Thanks for all your contributions! @cd1989

**Pull request merged**
