### PR TITLE
propose to add tracing

### PR DESCRIPTION
**Pull request by ninjadq**
Signed-off-by: DQ <dengq@vmware.com>

### CODE REVIEW

**Comment by renmaosheng** [comment]
could you please add the user workflow in the proposal? thanks.

**Review by wy65701436 — APPROVED** [review]
lgtm

**Comment by OrlinVasilev** [comment]
@ninjadq I think we can close merge that now since it was released?

**Comment by OrlinVasilev** [comment]
Implemented and released in 2.4.

**Review by OrlinVasilev — APPROVED** [review]
implemented

**Review by Vad1mo — APPROVED** [review]

**Review by yanji09 — APPROVED** [review]
LGTM

**Pull request merged**
