### PR TITLE
updating the leadership team for Harbor

### PR DESCRIPTION
**Pull request by michmike**
hi everyone, 

I am leaving VMware to join a Nuvalence.io and as a result I am scaling down my involvement in Harbor and Open Source and stepping down as a maintainer. We have had a tremendous last two years in the Harbor community and I would like to congratulate you all on this amazing journey. It has been a privilege to be a product lead for Harbor for this time and I look forward to seeing great things from you all. I will pitch Harbor as a registry at every stop.

Signed-off-by: Michael Michael <michmike@cs.stanford.edu>

### CODE REVIEW

**Review by xaleeks — APPROVED** [review]
It's sad to see you step down, Michael.  This project profited immensely from your leadership and expertise in the field.  But I'm sure we'll catch you at future open source meetups!

**Review by steven-zou — APPROVED** [review]
What a pity! We will miss you, @michmike. Thanks a lot for everything you did for the Harbor community!

**Review by mmpei — APPROVED** [review]
Wish you a bright future!

**Review by danielpacak — APPROVED** [review]
It has been a pleasure to work with you @michmike . Wish you all the success in your new job!

**Comment by michmike** [comment]
thank you @xaleeks , @steven-zou, @danielpacak, and @mmpei  for the kind words.

**Comment by holyhope** [comment]
I hope to see you again in many future projects.

**Comment by michmike** [comment]
thank you @holyhope

**Pull request merged**
