### PR TITLE
Proposal/a go cli tool for harbor

### PR DESCRIPTION
**Pull request by moooofly**
This proposal provides a command line interface (CLI) tool based on project harbor's REST APIs to
try to facilitate CI/CD process.

There are some common use cases:

- As an analysis tool to watch tags status and make deletion as your wish.
- As a debug tool to debug online issues, especially by checking logs, such as when replication error happens between endpoints.
- As a common tool to facilitate CI/CD process.

There are some related issues in the community:

* [goharbor/harbor#5285](https://github.com/goharbor/harbor/issues/5285) - how i can get project id by project name
* [goharbor/harbor#5165](https://github.com/goharbor/harbor/issues/5165) - Imcomplete results return by "/api/search" API
* [goharbor/harbor#5085](https://github.com/goharbor/harbor/issues/5085) - Harbor registry tag cleaner tool

Created from [goharbor/harbor#5703](https://github.com/goharbor/harbor/issues/5703). Opened a PR with the proposal here at the request of @steven-zou.

### CODE REVIEW

**Comment by clouderati** [comment]
Thanks @moooofly – I absolutely _love_ the idea of having a CLI client for Harbor like this; deeply grateful for your willingness to contribute your hard work to make this happen.

A few outstanding questions / thoughts we should all discuss:
- I think we should keep with the trend of naming CLI tools `-ctl`; in this case we'd pick something like `harborctl` for the binary name. Thoughts?
- Is the goal to bring the project into the `goharbor` org, or into the actual `goharbor/harbor` repo? My 2¢: org is fine, but I'd rather keep it separate from the main repo
- Longer term, are there any objections to making the syntax a bit more "UNIX-y"? i.e., we'd aim for something like `harborctl tags list` as opposed to `harborctl get_tags`.

Thanks again @moooofly!

**Comment by moooofly** [comment]
Thanks for giving more perspective. @clouderati 

- I will change the binary name from `harbor-go-client` into `harborctl` for keeping with the trend of naming convention.
-  I'd rather keep it separate from the main repo too.
- I can't agree with you more. I will change the syntax.

Thanks agent @clouderati

**Comment by clouderati** [comment]
@goharbor/harbor ptal and comment. Let's discuss during next community call.

**Comment by clouderati** [comment]
Hi @moooofly – how are things looking with this proposal? Anything we can help with? Happy to jump in and help polish this up. Looking forward to finally having a proper CLI for Harbor!

**Comment by moooofly** [comment]
I'm agree with what you said, thanks for you help, @nlowe

**Comment by clouderati** [comment]
Completely agree @nlowe.

@moooofly I know you're busy; no pressure! Happy to help in any way that we can.

**Comment by moooofly** [comment]
There is a doubt about: should I change repo's name from `moooofly/harbor-go-client` to `moooofly/harborctl`, or just rename binary file?

**Comment by steven-zou** [comment]
> harborctl

@moooofly 

I prefer `harborctl`. What's the overall progress of the implemetation?

**Comment by moooofly** [comment]
@steven-zou 

I have created a new repo named "harborctl", and I'm working on it.

- Use cmd framework (viper & cobra)
- refactor old redundant codes
- try to be compliant with habror v1.6.0

here is current progress:

```
[#774#root@ubuntu-1604 /go/src/github.com/moooofly/harborctl]$./harborctl -h
This project offer a command-line interface to the Harbor API, you can use it to manager your users, projects, repositories, etc.

Usage:
  harborctl [command]

Available Commands:
  help        Help about any command
  login       Log in to Harbor.
  logout      Log out from Harbor.
  project     API of '/projects'.
  search      Search for projects and repositories.

Flags:
      --config string   config file (default is $HOME/, working dir (.), and ./conf dir)
  -h, --help            help for harborctl
  -t, --toggle          Help message for toggle

Use "harborctl [command] --help" for more information about a command.
```

The complete project subcommand for "/projects" API.

```
[#775#root@ubuntu-1604 /go/src/github.com/moooofly/harborctl]$./harborctl project -h
The collection of '/projects' API.

Usage:
  harborctl project [flags]
  harborctl project [command]

Available Commands:
  create      Create a new project.
  delete      Delete a project by project_id.
  get         Get a project by project_id.
  list        List all projects by filter.
  update      Update properties for a selected project by project_id.

Flags:
  -h, --help   help for project

Global Flags:
      --config string   config file (default is $HOME/, working dir (.), and ./conf dir)

Use "harborctl project [command] --help" for more information about a command.
[#776#root@ubuntu-1604 /go/src/github.com/moooofly/harborctl]$./harborctl project create -h
This endpoint is for user to create a new project.

Usage:
  harborctl project create [flags]

Flags:
  -a, --automatically_scan_images_on_push                        Whether scan images automatically when pushing.
  -t, --enable_content_trust                                     Whether content trust is enabled or not. If it is enabled, user cann't pull unsigned images from this project.
  -h, --help                                                     help for create
  -r, --prevent_vulnerable_images_from_running                   Whether prevent the vulnerable images from running.
  -s, --prevent_vulnerable_images_from_running_severity string   If the vulnerability is high than severity defined here, the images cann't be pulled.
  -n, --project_name string                                      (REQUIRED) The name of the project.
  -k, --public int32                                             The public status of the project, public(1) or private(0). (default 1)

Global Flags:
      --config string   config file (default is $HOME/, working dir (.), and ./conf dir)
[#777#root@ubuntu-1604 /go/src/github.com/moooofly/harborctl]$./harborctl project delete -h
This endpoint is aimed to delete a project by project_id.

Usage:
  harborctl project delete [flags]

Flags:
  -h, --help               help for delete
  -j, --project_id int32   (REQUIRED) Project ID of project which will be deleted.

Global Flags:
      --config string   config file (default is $HOME/, working dir (.), and ./conf dir)
[#778#root@ubuntu-1604 /go/src/github.com/moooofly/harborctl]$./harborctl project get -h
This endpoint returns specific project information by project_id.

NOTE: This endpoint can be used without cookie.

Usage:
  harborctl project get [flags]

Flags:
  -h, --help               help for get
  -j, --project_id int32   (REQUIRED) Project ID of project which will be get.

Global Flags:
      --config string   config file (default is $HOME/, working dir (.), and ./conf dir)
[#779#root@ubuntu-1604 /go/src/github.com/moooofly/harborctl]$./harborctl project list -h
This endpoint returns all projects created by Harbor which can be filtered by (project) name, owner and public property.

NOTE: This endpoint can be used without cookie.

Usage:
  harborctl project list [flags]

Flags:
  -h, --help              help for list
  -n, --name string       The name of project.
  -o, --owner string      The name of project owner.
  -p, --page int32        The page nubmer, default is 1. (default 1)
  -s, --page_size int32   The size of per page, default is 10, maximum is 100. (default 10)
  -k, --public string     The project is public or private.

Global Flags:
      --config string   config file (default is $HOME/, working dir (.), and ./conf dir)
[#780#root@ubuntu-1604 /go/src/github.com/moooofly/harborctl]$./harborctl project update -h
This endpoint is aimed to update the properties of a project.

Usage:
  harborctl project update [flags]

Flags:
  -a, --automatically_scan_images_on_push                        Whether scan images automatically when pushing.
  -t, --enable_content_trust                                     Whether content trust is enabled or not. If it is enabled, user cann't pull unsigned images from this project.
  -h, --help                                                     help for update
  -r, --prevent_vulnerable_images_from_running                   Whether prevent the vulnerable images from running.
  -s, --prevent_vulnerable_images_from_running_severity string   If the vulnerability is high than severity defined here, the images cann't be pulled.
  -j, --project_id int32                                         (REQUIRED) Project ID of project which will be update.
  -n, --project_name string                                      The name of the project.
  -k, --public int32                                             The public status of the project, public(1) or private(0). (default 1)

Global Flags:
      --config string   config file (default is $HOME/, working dir (.), and ./conf dir)
[#781#root@ubuntu-1604 /go/src/github.com/moooofly/harborctl]$
```

**Comment by clouderati** [comment]
Wahoo – great progress @moooofly!

**Comment by clouderati** [comment]
@moooofly can you please squash your commits so that we can merge? Thanks!

**Comment by moooofly** [comment]
UPDATE: close this by mistake, open a new one at https://github.com/goharbor/community/pull/18 .

**Pull request closed without merging**
