### PR TITLE
chore[community]: nominate pierre as maintainer

### PR DESCRIPTION
**Pull request by steven-zou**
Signed-off-by: Steven Zou <szou@vmware.com>

I'm so glad to nominate [Pierre PÉRONNET](github.com/holyhope) from [OVH Cloud](https://www.ovh.com/world/) to be the maintainer of the Harbor community. Pierre is one of the creators of [harbor-operator](https://github.com/goharbor/harbor-operator) project and he'll continue to maintain and do significant contributions to that exciting project in the future. 

IMO, Pierre is qualified as a Harbor maintainer and I believe he will do more contributions to both Harbor community and the governed projects with the maintainer role in the future.

Here is Pierre's bio:

>Pierre PÉRONNET: Working since 2016 at OVHcloud to industrialize application deployments in hyper-scalable infrastructures. I am at the origin of the Harbor Operator project. I designed it, developing it and using it at scale.
Technical lead of the Managed private registry product, long term contributor of the Kubernetes managed by OVHcloud. I am passionate about cloud-native, automation and standardization.

### CODE REVIEW

**Comment by mmpei** [comment]
lgtm

**Comment by steven-zou** [comment]
@goharbor/maintainers 

Please review and give votes to this nomination, thanks!

**Comment by michmike** [comment]
+1 Binding

**Comment by michmike** [comment]
@steven-zou  does the last name have to be capitalized?

**Comment by steven-zou** [comment]
> @steven-zou does the last name have to be capitalized?

@michmike 

No. I just copied the name from their email and did not do any changes.  I think the name havve not to be capitalized.

**Comment by steven-zou** [comment]
> 2/3 votes got, nomination approved.

**Pull request merged**
