### PR TITLE
feat: add harbor perf testing framework proposal

### PR DESCRIPTION
**Pull request by chlins**
Signed-off-by: chlins <chlins.zhang@gmail.com>

### CODE REVIEW

**Comment by yanji09** [comment]
What‘s the difference b/w metrics '90% requests response time' and '95% requests response time'?

**Comment by chlins** [comment]
> What‘s the difference b/w metrics '90% requests response time' and '95% requests response time'?

@yanji09 The difference between them is only the percentage of requests, there is no other difference, and these different percentages are often used as a comparison in performance testing.

**Review by wy65701436 — APPROVED** [review]
lgtm

**Review by heww — APPROVED** [review]

**Review by yanji09 — APPROVED** [review]
LGTM

**Pull request merged**
