### PR TITLE
Proposal for CSV export of vulnerability data from Harbor

### PR DESCRIPTION
**Pull request by prahaladdarkin**
Detailed  technical proposal for exporting vulnerability scan data as CSV.

### CODE REVIEW

**Comment by OrlinVasilev** [comment]
@goharbor/all-maintainers can someone check that please

**Review by Vad1mo — COMMENTED** [review]
I think we can close this one as https://github.com/goharbor/community/pull/181 also by @prahaladdarkin does also address this proposal. 

Am I correct @prahaladdarkin ?

**Comment by Vad1mo** [comment]
@prahaladdarkin any updates on your proposal?

**Comment by prahaladdarkin** [comment]
@Vad1mo apologize for this delayed response. This proposal was under developement and had a dependency on the completion of the system artifact manager: https://github.com/goharbor/community/pull/181.

The development work for the system artifact manager and the integration has completed. I will be updating this proposal with the latest and greatest of the design changes.

**Comment by pthoelken** [comment]
Maybe it's also possible to add the function for exporting as PDF to sending these PDF file to Managers or other persons which don't have access to harbor and only needs the vulnerability informations? Thanks in advanced.

**Review by wy65701436 — APPROVED** [review]
lgtm

**Comment by prahaladdarkin** [comment]
@pthoelken  thank you for your input and indeed we can also generate PDF reports. However, the current scope of the implementation is restricted to generating the CSV data for the vulnerability information. CSV files also have the additional advantage of being able to be consumed in downstream analytics tools (including spreadsheet software like MS Excel). 
Please feel free to open an enhancement issue for PDF data and that can be prioritized based on discussions in the community :)

**Comment by chlins** [comment]
@616b2f Hi, this feature was delivered in the Harbor v2.6.

**Review by chlins — APPROVED** [review]
lgtm

**Review by Vad1mo — APPROVED** [review]

**Comment by Udayendu** [comment]
@Vad1mo, any idea by when this feature will be available ?

**Comment by Udayendu** [comment]
@OrlinVasilev / @prahaladdarkin,

I am using v2.10.1 with trivy v0.49.1 but still can't see the export pdf button under the Vulnerabilities tab. Only the following options are available.

image

As per @chlins , this feature was delivered in Harbor v2.6. Not sure why its not visible in the UI, am I missing anything ??

**Comment by dpetiz** [comment]
> @OrlinVasilev / @prahaladdarkin,
> 
> I am using v2.10.1 with trivy v0.49.1 but still can't see the export pdf button under the Vulnerabilities tab. Only the following options are available.
> 
> image
> 
> As per @chlins , this feature was delivered in Harbor v2.6. Not sure why its not visible in the UI, am I missing anything ??

Version 2.10.2 without too

**Comment by hajnalmt** [comment]
This feature was implemented to generate CSV exports only and can be triggered from the Projects page as an Action.
Although the pdf report would have been a nice addition, and the API has it as a format type, it doesn't work and gives back a csv.

**Pull request merged**
