### PR TITLE
chore(nominations):nominate alex xu as maintainer

### PR DESCRIPTION
**Pull request by steven-zou**
hi @goharbor/maintainers 

I'm so glad to nominate Alex Xu(@xaleeks) as our new maintainer. Alex will continue to focus on the product management of the Harbor project(s) and promote the rapid development of the harbor project and community for the next greater achievements. Alex has been:

* maintaining the overall roadmap of Harbor and will do contributions to the release plans
  * check [Harbor Project Board](https://github.com/orgs/goharbor/projects/1)
  * check [Roadmap](https://github.com/goharbor/harbor/blob/master/ROADMAP.md)
* regularly hosting the community meetings
* triaging kinds of requirements from the community and deeply diving valuable ones
* supervising feature development via PRDs
* speaking Harbor in kinds of conferences(e.g: KubeCon) and webinars
* collaborating with upstream/downstream teams to expand Harbor influences
* promoting production adoptions of Harbor
* starting to do more ...

IMO, Alex is qualified as a Harbor maintainer and I believe he will do more contributions with the maintainer role in the future.

Attach his BIO here:
>“I’m a product manager in the Cloud Native team at VMware, working on image registries for containerized workloads across private and public clouds.  I’m also the PM for Harbor (GitHub:goharbor), a popular open-source enterprise-grade registry for managing OCI artifacts such as docker images, helm charts, OPAs, and much more.  Prior to that, I worked on virtualization technologies, distributed filesystems, and PV storage for docker containers.”

Signed-off-by: Steven Zou <szou@vmware.com>

### CODE REVIEW

**Comment by steven-zou** [comment]
@goharbor/all-maintainers 

Please review and votes. Thanks!

**Comment by kofj** [comment]
Welcome🎉

**Comment by michmike** [comment]
+1 approved
well deserved @xaleeks

**Comment by steven-zou** [comment]
@goharbor/all-maintainers 

I think we got the supermajority of votes from the existing maintainers. Thie nomination request is approved. Alex xu( @xaleeks) now formally becomes the maintainer of Harbor.

Let's welcome Alex to join the Harbor maintainer group!

**Pull request merged**
