### PR TITLE
Move Tianon to Emeritus Maintainers

### PR DESCRIPTION
**Pull request by tianon**
I had hoped to continue contributing, but I unfortunately do not have the bandwidth anymore [in my new role at Docker, Inc](https://www.docker.com/blog/docker-acquires-long-time-partner-infosiftr/), and I felt it was doing the project a disservice to keep me listed here. :two_hearts:

Collaborating here has been a privilege, and I'm definitely still open to helping out where I can, especially if there are conversations where my knowledge might be useful! :+1:

(Sorry @OrlinVasilev -- I know we've been trying to connect for weeks :see_no_evil: :heart:  Hopefully you can understand!)

### CODE REVIEW

**Comment by tianon** [comment]
(Unfortunately, this also means that someone else will probably want to pick up #170 and take it across the finish line :sweat_smile:)

**Comment by Vad1mo** [comment]
I am very sorry to hear this! I wish you the best in your next endeavors.

**Comment by OrlinVasilev** [comment]
Hi @tianon , somehow I was seeing this one coming :(

I was really hopping that Docker will be joining the community and you can be still part or the team! :)
Maybe you can reconsider at some point :)

Good luck at your new adventures!

Thanks for all your work and dedication!
Orlix

**Review by OrlinVasilev — APPROVED** [review]
It doesn't look good to me but I approve! :(

**Review by Vad1mo — APPROVED** [review]

**Comment by tianon** [comment]
Would it be helpful for me to combine #170 into this one? (since they're touching the same lines)

**Comment by Vad1mo** [comment]
> Would it be helpful for me to combine #170 into this one? (since they're touching the same lines)

Yes, the #170 has merge conflicts and I can't resolve them.

**Review by OrlinVasilev — APPROVED** [review]

**Comment by tianon** [comment]
Updated to include relevant changes from #170 :+1:

**Review by Vad1mo — APPROVED** [review]

**Review by OrlinVasilev — APPROVED** [review]

**Comment by OrlinVasilev** [comment]
@qnetter can you please approve!

**Review by qnetter — APPROVED** [review]
LGTM!

**Comment by OrlinVasilev** [comment]
With great reluctance Merged! :(

**Pull request merged**
