### PR TITLE
Create GUIDING_PRINCIPLES.md

### PR DESCRIPTION
**Pull request by michmike**
@goharbor/all-maintainers  please vote on this set of guiding principles for our project.
/hold
Signed-off-by: Michael Michael <michmike@users.noreply.github.com>

### CODE REVIEW

**Comment by michmike** [comment]
> What's the difference with the existing governance model?

@steven-zou the governance model talks about how decisions are made and by whom's authority. this document talks about the values and principles of the project and how we apply them in making decisions.

**Comment by steven-zou** [comment]
@michmike 

I'm still confused by this proposal.  The main concern is the boundary between this committee and the harbor core maintainers is not clear. Seems the responsibilities of this committee and the harbor core maintainer group have a lot of overlaps: the committee needs to confirm the community follows the values and principles defined here, and the core maintainer group is responsible for the `overall health` of the community.  

>Core Maintainers: Responsible for the overall health and direction of the project; final reviewers of PRs and responsible for releases.

And moreover, will the decisions made by this committee be reviewed and approved by the core maintainer group or directly performed to the community operations? What's the relationship between these two groups after the committee is setup?

Why do we need to define it here? Why not do modifications to the governance model? Am I missing something and then cause those misunderstandings?

ps: Is it required by CNCF or is it because we need to match some expectations for achieving our next step?

**Comment by michmike** [comment]
> @michmike
> 
> I'm still confused by this proposal. The main concern is the boundary between this committee and the harbor core maintainers is not clear. Seems the responsibilities of this committee and the harbor core maintainer group have a lot of overlaps: the committee needs to confirm the community follows the values and principles defined here, and the core maintainer group is responsible for the `overall health` of the community.
> 
> > Core Maintainers: Responsible for the overall health and direction of the project; final reviewers of PRs and responsible for releases.
> 
> And moreover, will the decisions made by this committee be reviewed and approved by the core maintainer group or directly performed to the community operations? What's the relationship between these two groups after the committee is setup?
> 
> Why do we need to define it here? Why not do modifications to the governance model? Am I missing something and then cause those misunderstandings?
> 
> ps: Is it required by CNCF or is it because we need to match some expectations for achieving our next step?

@steven-zou i updated it a little bit to make it clearer. Essentially, it is not two groups making decisions. The maintainers group is still responsible for Harbor. that includes everything from technical decisions, direction of the project and overall health. The committee that upholds the values of the project includes only the core maintainers and Jonas. This committee can't make any decisions. However they monitor the community interactions and look for cases where the Harbor values are not being met and flag that up to the community.

this is not required by CNCF, but it an integral part of creating a community with a shared vision and goals

**Comment by michmike** [comment]
@steven-zou  i clarified the content a little bit more to make it clear  around how we enforce the guiding principles. i hope this solves some of the concerns you have.

we will not change our project governance now, but we should make a plan to discuss that in the next maintainers meeting. you bring up a lot of good and valuable points why that change is needed

**Pull request merged**
