### PR TITLE
Add chart signature verification proposal

### PR DESCRIPTION
**Pull request by steven-zou**
**Add chart signature verification proposal**
- add _content folder for keeping the images used in the proposal

Signed-off-by: Steven Zou <szou@vmware.com>

### CODE REVIEW

**Comment by lweitzman** [comment]
Attached images and those mockups can be seen here: https://vmware.invisionapp.com/share/RKOJ1Q83XNS#/340495007_v1-8_-_Helm_Charts

**Comment by lweitzman** [comment]
image001
image002
image003
image004
image005
image006

**Comment by OrlinVasilev** [comment]
@steven-zou is that still valid or we can close it?

**Comment by wy65701436** [comment]
@steven-zou we can close it since the chartmuseum was planned to be deprecated.

**Comment by Vad1mo** [comment]
I think we should maybe support https://github.com/sigstore/helm-sigstore instead as habor does already support sigstore

**Comment by OrlinVasilev** [comment]
closing as we are deprecating chart museum

**Pull request closed without merging**
