### PR TITLE
Create image_cve_to_work_on_push.md

### PR DESCRIPTION
**Pull request by arnaudclerc**
new feature proposal to granularly configure how to possibly fix CVE

### CODE REVIEW

**Comment by OrlinVasilev** [comment]
@arnaudclerc - fantastic ! can you please add that proposal for next week agenda for community meeting  if you can present it ?

**Comment by OrlinVasilev** [comment]
@arnaudclerc we can add that into the list but we need resources to work on that! Thank you for contributing! @msha01 for visibility! :)

**Comment by OrlinVasilev** [comment]
@arnaudclerc why did you close that one?

**Comment by arnaudclerc** [comment]
in the issue discussion, we discovered that the behaviour wasn't happening when using Docker CLI, so it has been deducted that Harbor doesn't require this feature.
The feature can still be implemented but i don't see a real urgent need for it.

The bug was driven by Kaniko, I still don't know what tool's mechanisms make it so different than a regular push via Docker 

[#227](https://github.com/goharbor/harbor/issues/18792)

**Comment by OrlinVasilev** [comment]
Thank you!!! @arnaudclerc

**Pull request closed without merging**
