### PR TITLE
Pull images from Docker Hub to Harbor

### PR DESCRIPTION
**Pull request by cd1989**
Signed-off-by: 陈德 <chende@caicloud.io>

### CODE REVIEW

**Comment by steven-zou** [comment]
@cd1989 

Is it possible to merge this PR into #21? We can use that thread to discuss the replication NEXT. I'm planning to build a work group working on the replication service.

**Comment by clouderati** [comment]
@steven-zou isn't #21 equivalent to pushing images _from_ Harbor _to_ a cloud-based registry, while this is pulling images _from_ a cloud-based registry _to_ Harbor?

**Comment by steven-zou** [comment]
@clouderati 

I have noticed that they should be in separate PRs.

For delivering work, we can aggregate/merge the team as a workgroup because these two PRs both need to refactor the fundamental models and interfaces.

**Comment by clouderati** [comment]
> For delivering work, we can aggregate/merge the team as a workgroup because these two PRs both need to refactor the fundamental models and interfaces.

Ah yes, great idea. :+1:

**Comment by reasonerjt** [comment]
Should this be dup to #40 ?

**Comment by steven-zou** [comment]
@cd1989 

Let's cover the work proposed here with PR https://github.com/goharbor/community/pull/40 and close this one.

**Pull request closed without merging**
